# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Prepare env"
          command: "sudo apt update -y && sudo apt-get update -y && sudo apt upgrade -y && sudo apt install neofetch bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev -y"
      - run:
          name: "Prepare repo"
          command: "neofetch && df -h && PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo"
      - run:
          name: "Repo init"
          command: "mkdir los21 && cd los21 && git config --global color.ui false && git config --global user.name onesmiledx && git config --global user.email beksultanbazuov@gmail.com && repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --depth=1 --git-lfs && git clone https://github.com/samsung-mt6765-devs/local_manifests .repo/local_manifests && repo sync --force-sync -j36"
      - run:
          name: "Start build"
          command: "cd /home/circleci/project/los21 && rm -rf .repo && source build/envsetup.sh && lunch lineage_a10s-ap2a-userdebug && mka bootimage -j36"
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  lineage-21-build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
